### ISSUE TITLE
Twitter query: what's the query length size limit ?

### ISSUE THREAD

**Issue by aborruso** [CJWorkbench/cjworkbench#136]
Hi,
I have built this query "[(min_retweets:10) OR (min_faves:10) opendata OR ("open data") OR ("dati aperti") OR ("dati pubblici") OR ("dato aperto") OR ("dato pubblico") OR ("données publiques") OR ("Verwaltungsdaten festgelegt") OR ("offene Verwaltungsdaten") OR ("DATOS ABIERTOS") OR ("avoin data") OR "avoindata" OR "datosabiertos" OR DadesObertes OR ("DadesObertes") dadosabertos OR ("dados abertos")](https://twitter.com/search?q=(min_retweets%3A10)%20OR%20(min_faves%3A10)%20opendata%20OR%20(%22open%20data%22)%20OR%20(%22dati%20aperti%22)%20OR%20(%22dati%20pubblici%22)%20OR%20(%22dato%20aperto%22)%20OR%20(%22dato%20pubblico%22)%20OR%20(%22donn%C3%A9es%20publiques%22)%20OR%20(%22Verwaltungsdaten%20festgelegt%22)%20OR%20(%22offene%20Verwaltungsdaten%22)%20OR%20(%22DATOS%20ABIERTOS%22)%20OR%20(%22avoin%20data%22)%20OR%20%22avoindata%22%20OR%20%22datosabiertos%22%20OR%20DadesObertes%20OR%20(%22DadesObertes%22)%20dadosabertos%20OR%20(%22dados%20abertos%22)&src=typed_query&f=live)", but it does not work in workbenchdata.

If I use this shorter one "[(min_retweets:10) OR (min_faves:10) opendata OR ("open data") OR ("dati aperti") OR ("dati pubblici") OR ("dato aperto") OR ("dato pubblico") OR ("données publiques") OR ("Verwaltungsdaten festgelegt") OR ("offene Verwaltungsdaten") OR ("DATOS ABIERTOS") OR ("avoin data") OR "avoindata"](https://twitter.com/search?q=(min_retweets%3A10)%20OR%20(min_faves%3A10)%20opendata%20OR%20(%22open%20data%22)%20OR%20(%22dati%20aperti%22)%20OR%20(%22dati%20pubblici%22)%20OR%20(%22dato%20aperto%22)%20OR%20(%22dato%20pubblico%22)%20OR%20(%22donn%C3%A9es%20publiques%22)%20OR%20(%22Verwaltungsdaten%20festgelegt%22)%20OR%20(%22offene%20Verwaltungsdaten%22)%20OR%20(%22DATOS%20ABIERTOS%22)%20OR%20(%22avoin%20data%22)%20OR%20%22avoindata%22&src=typed_query&f=live)", it works.

What's the query length size limit ?

Thank you

**Comment by adamhooper** [comment]
https://developer.twitter.com/en/docs/tweets/search/api-reference/get-search-tweets.html suggests the limit _should_ be 500 characters. Your query is certainly shorter than that. We'll look into it.

**Comment by adamhooper** [comment]
I finally looked into this.

The query size limit is 500 URL-encoded characters. Your big query is 497. so it's valid. Twitter runs it and returns no results.

Why no results? Because there is no tweet matching that query within the past 7 days. (The most recent tweet is Aug. 9.) According to the [Twitter API docs](https://developer.twitter.com/en/docs/tweets/search/api-reference/get-search-tweets):

> Keep in mind that the search index has a 7-day limit. In other words, no tweets will be found for a date older than one week.

If this surprises you, it's probably because your search seems to have a typo: it's missing an OR next to "dadosabertos". This works for me:

(min_retweets:10) OR (min_faves:10) opendata OR ("open data") OR ("dati aperti") OR ("dati pubblici") OR ("dato aperto") OR ("dato pubblico") OR ("données publiques") OR ("Verwaltungsdaten festgelegt") OR ("offene Verwaltungsdaten") OR ("DATOS ABIERTOS") OR ("avoin data") OR "avoindata" OR "datosabiertos" OR DadesObertes OR ("DadesObertes") OR dadosabertos OR ("dados abertos")

**Comment by aborruso** [comment]
Hi @adamhooper the error was in syntax. I had to add an `OR`.

From

```
(min_retweets:10) 
OR (min_faves:10) opendata 
OR ("open data") 
OR ("dati aperti") 
OR ("dati pubblici") 
OR ("dato aperto") 
OR ("dato pubblico") 
OR ("données publiques") 
OR ("Verwaltungsdaten festgelegt") 
OR ("offene Verwaltungsdaten") 
OR ("DATOS ABIERTOS") 
OR ("avoin data") 
OR "avoindata" 
OR "datosabiertos" 
OR DadesObertes 
OR ("DadesObertes") dadosabertos 
OR ("dados abertos")
```

to

```
(min_retweets:10) 
OR (min_faves:10) opendata 
OR ("open data") 
OR ("dati aperti") 
OR ("dati pubblici") 
OR ("dato aperto") 
OR ("dato pubblico") 
OR ("données publiques") 
OR ("Verwaltungsdaten festgelegt") 
OR ("offene Verwaltungsdaten") 
OR ("DATOS ABIERTOS") 
OR ("avoin data") 
OR "avoindata" 
OR "datosabiertos" 
OR DadesObertes 

OR ("DadesObertes") OR dadosabertos 

OR ("dados abertos")
```

Thank you for your time
