### ISSUE TITLE
Suggested system resources

### ISSUE THREAD

**Issue by mpiccolino-tealblue** [CJWorkbench/cjworkbench#267]
What would be the recommended specs for running CJW on a development machine?

**Comment by adamhooper** [comment]
Not quite sure ... 2GB should be fine and there's no lower bound on the amount of CPU.

**Comment by mpiccolino-tealblue** [comment]
Thanks Adam. I've given it a go on an i5 macmini, 4Gb, with ubuntu server. I tried a few CSV datasets which comprise a handful of columns and some 50 rows, it mostly seems to hang (spinning "busy" icon) after one or two steps. The server logs printed on screen do not highlight anything in particular. What would be the best way to try and understand what's going on? Thanks.

**Comment by adamhooper** [comment]
* `docker ps -a` => are any processes stopped?
* web-browser JavaScript console: are there any messages?
* If you refresh the page, do you still see a spinner? (Websockets are tricky; reloading the page will work even when websockets break)
* Can you implement your workflow using a "paste" step instead of an "upload" step? (Copy/paste the entire CSV)

**Comment by mpiccolino-tealblue** [comment]
- No stopped processes
- "Websocket closed. Reconnecting in 1000ms" this is printed when doing Ctrl+R, it seems
- yes
- I need to check this, I'm not a vim user and I only have a minimal GUI with browser on this machine

Here's a sample dataset: https://data2.unhcr.org/population/get/origin?export=csv&widget_id=261209&sv_id=11&population_group=4924&population_collection=28&limit=10&fromDate=2021-01-01

(requires Split columns)

**Comment by adamhooper** [comment]
This could happen if one of the steps is never completing.

The problem could arise because your dataset is UTF-16. Workbench is _meant_ to support that encoding, but it's uncommon and there might be a bug there. So the "paste" approach would fix it:

1. Open your CSV in a text file
2. Copy the contents
3. Paste them into a "Paste" step

But you'll need to `bin/dev stop && bin/dev start` first -- otherwise, Workbench will continue trying to render your step.

**Comment by mpiccolino-tealblue** [comment]
Thanks Adam, I'll check it out.
Marco

Il Gio 16 Set 2021, 14:56 Adam Hooper ***@***.***> ha scritto:

**Comment by mpiccolino-tealblue** [comment]
Indeed it looks like it was an issue with that particular resource - loading other kind of data worked well.
Many thanks!
