### ISSUE TITLE
Changing processing limits for local instance

### ISSUE THREAD

**Issue by mpiccolino-tealblue** [CJWorkbench/cjworkbench#268]
Where can I change processing limits (e.g. max number of importable rows) for a local CJW instance?

**Comment by adamhooper** [comment]
Edit [cjwkernel/settings.py](https://github.com/CJWorkbench/cjworkbench/blob/master/cjwkernel/settings.py) to set data limits. These aren't configurable by environment variable because we've never encountered a use case.

Modifying `cjwkernel/settings.py` stuff doesn't change CPU/RAM requirements at all. You can always write a Python step that consumes 100% of all CPU and RAM. We limit CPU/RAM in Kubernetes, not in CJWorkbench; and there is no limiting mechanism in development mode. The main goal of `cjworkbench/settings.py` is to produce gentler error messages and nudge users towards patterns we've prepared for.
